# Generated by Django 5.1.1 on 2024-10-08 16:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="consultancy"),
                ),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Province 1", "Province 1"),
                            ("Province 2", "Province 2"),
                            ("Bagmati", "Bagmati"),
                            ("Gandaki", "Gandaki"),
                            ("Lumbini", "Lumbini"),
                            ("Karnali", "Karnali"),
                            ("Sudurpashchim", "Sudurpashchim"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=15, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Consultancies",
                "db_table": "consultancy",
            },
        ),
    ]
