# Generated by Django 5.1.1 on 2024-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_consultancy_is_approved_consultancy_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultancy",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
