# Generated by Django 5.1.1 on 2024-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_consultancy_address_alter_consultancy_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultancy",
            name="company_email",
            field=models.EmailField(
                default="comany@gmail.com", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
