# Generated by Django 5.1.1 on 2024-10-09 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_consultancy_company_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultancy",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
