# Generated by Django 5.1.1 on 2024-10-09 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_consultancy_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="associated_consultancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="users.consultancy",
            ),
        ),
    ]
