# Generated by Django 5.1.1 on 2024-10-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_associated_consultancy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="associated_consultancy",
            new_name="associated_with",
        ),
    ]
