# Generated by Django 5.1.1 on 2024-11-12 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_associated_with"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultancy",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultancy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
