# Generated by Django 5.1.1 on 2024-10-09 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("temporary_address", models.CharField(max_length=255)),
                ("temporary_city", models.CharField(max_length=100)),
                ("temporary_state", models.CharField(max_length=100)),
                ("temporary_country", models.CharField(max_length=100)),
                ("temporary_zip_code", models.CharField(max_length=10)),
                ("permanent_address", models.CharField(max_length=255)),
                ("permanent_city", models.CharField(max_length=100)),
                ("permanent_state", models.CharField(max_length=100)),
                ("permanent_country", models.CharField(max_length=100)),
                ("permanent_zip_code", models.CharField(max_length=10)),
                ("passport_number", models.CharField(max_length=255)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("issue_country", models.CharField(max_length=100)),
                ("city_of_birth", models.CharField(max_length=100)),
                ("country_of_birth", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=100)),
                ("citizenship", models.CharField(max_length=100)),
                ("emergency_contact_relationship", models.CharField(max_length=100)),
                ("emergency_contact_phone", models.CharField(max_length=15)),
                ("emergency_contact_email", models.EmailField(max_length=150)),
                ("emergency_contact_name", models.CharField(max_length=150)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Profiles",
                "db_table": "profile",
            },
        ),
    ]
