# Generated by Django 5.1.1 on 2024-10-09 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("grade 12 or equivalent", "Grade 12 or equivalent"),
                            ("undergraduate", "Undergraduate"),
                            ("postgraduate", "Postgraduate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("university_name", models.CharField(max_length=255)),
                ("qualification_achieved", models.CharField(max_length=255)),
                (
                    "gpa_system",
                    models.CharField(
                        choices=[
                            ("4.0", "4.0"),
                            ("5.0", "5.0"),
                            ("7.0", "7.0"),
                            ("10.0", "10.0"),
                            ("100.0", "100.0"),
                        ],
                        max_length=10,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "backlogs",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("language", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Education",
                "db_table": "education",
            },
        ),
    ]
