# Generated by Django 5.1.1 on 2024-10-09 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_education"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test",
                    models.CharField(
                        choices=[
                            ("ielts", "IELTS"),
                            ("toefl", "TOEFL"),
                            ("pte", "PTE"),
                            ("gre", "GRE"),
                            ("gmat", "GMAT"),
                            ("sat", "SAT"),
                            ("jlpt", "JLPT"),
                            ("korean language", "Korean Language"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("test_document", models.FileField(upload_to="test_documents/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Language Tests",
                "db_table": "language_test",
            },
        ),
    ]
