# Generated by Django 5.1.1 on 2024-10-09 17:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_languagetest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="languagetest",
            unique_together={("user", "test")},
        ),
    ]
