# Generated by Django 5.1.1 on 2024-10-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_languagetest_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagetest",
            name="score",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
