# Generated by Django 5.1.1 on 2024-10-10 04:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_alter_languagetest_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="education",
            unique_together={("user", "level")},
        ),
    ]
