# Generated by Django 5.1.1 on 2024-10-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_document_uploader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="uploader",
            field=models.CharField(
                choices=[("self", "Self"), ("consultancy", "Consultancy")],
                default="self",
                max_length=20,
            ),
        ),
    ]
